TOTAL=10
PRINT ADD(5)
PRINT FACT(5)
PRINT WRAP$("CPB")
END
FUNCTION ADD(X)
    GLOBAL TOTAL
    TOTAL=TOTAL+X
    RETURN TOTAL
END FUNCTION
FUNCTION FACT(N)
    IF N<=1 THEN RETURN 1
    RETURN N*FACT(N-1)
END FUNCTION
FUNCTION WRAP$(S$)
    RETURN "["+S$+"]"
END FUNCTION
