SELECT CASE F$()
CASE "YES","Y","OK"
    PRINT "MATCH"
CASE ELSE
    PRINT "OTHER"
END SELECT
PRINT "CALLS=";COUNT
END
FUNCTION F$()
    GLOBAL COUNT
    COUNT=COUNT+1
    RETURN "O"+"K"
END FUNCTION
