REM CREATE CPB094TEST DIRECTORY IN FILES BEFORE RUNNING
REM 50 CYCLES PER RUN; TAKE INFO AND SERIAL BETWEEN BATCHES
SCREEN 320,320
N=50
FOR I=1 TO N
    CLS
    COLOR 255,0,0
    BOX 8,8,40,40,1
    C=POINT(10,10)
    SAVEIMAGE "/CPB094TEST/ROUNDTRIP.BMP"
    SAVE IMAGE "/CPB094TEST/LEGACY.BMP"
    CLS
    LOADIMAGE "/CPB094TEST/ROUNDTRIP.BMP",0,0
    IF POINT(10,10)<>C THEN
        PRINT "IMAGE CHECK FAILED AT ";I
        STOP
    END IF
    CLS
    LOADIMAGE "/CPB094TEST/LEGACY.BMP",0,0
    IF POINT(10,10)<>C THEN
        PRINT "LEGACY CHECK FAILED AT ";I
        STOP
    END IF
NEXT I
PRINT "IMAGE CYCLES OK: ";N
